interface Event {
    _id: string; // auto generated by mongodb
    eventImageURL: string; // default empty string !
    eventName: string; // required !
    companyName: string; // required !
    shiftIDs: string[]; // _id's in ShiftSchema, required. Note: create shifts first, then create event so there are shiftIDs !
    categories: string[]; // required !
    description: string; // required !
    email: string; // required !
    coordinates?: string; // front end might need to change, required??
    address: string; // required !
    active?: boolean; // default True
    type: string; // required
    date: Date; // required
    deadline: Date; // required
    verified?: boolean; // default False
    role: string; // required
    requirements: string; // required
    url?: string; // required
    notes?: string; // default empty string
    edited?: boolean; // default False
    ageRestriction?: boolean;
    cprFirstAidCert?: boolean;
}

export default Event;
